# BASE/Configure.py
import os


initial_config = """
# This file was auto-generated by Configure.py, a custom module for Qumi Q3.
[UserData]
Username=Johndoe
Displayname=John Doe
Age=23
Gender=Male
Sexuality=Cisgender

[App-Specific]
Code=TTTTTT

[Critical]
# Don't touch unless you are an expert.
ToPT=1

# Neural Network QUtend
NeuralNetInputSize=3
NeuralNetHiddenSize=6
NeuralNetOutputSize=3

[Qumi_Data]
# Qumi's Info
QQName=Qumi
# UNIMPLEMENTED
# TODO: Let Qumi remember things. 
# - XiLy
QQMemoryFile=None
QQAge=14
QQDOB=4_5_26
QQTokenLimitMax=20 
# ^Sentence Length.^
QQLogFile=None
QQBecomeAware=False
QQBecomeMeaningful=False

[Qumi_Integrity]
# Basic Structure
QIModuleFoldeAI=API
QIQumiDataFolderName=QumiData
QIVocabJSONFileName=vocab.json
QISynapsesJSONFileName=synapses.json
QIBrainSystemDBFileName=brain.db

"""


class Configure:
    def __init__(self, config_file="QumiData\qu.conf", debug=False):
        self.config_file = config_file
        self.config = {}
        self.set_debug = debug

        self.product_code = self.get_config_value("Code")
        if self.product_code == "Transy":
            print("Code found...")
    
    def _create_if_not_exist(self):
        with open(self.config_file, "x") as f:
            f.write(initial_config)
    
    def get_config_value(self, namse):
        try:
            with open(self.config_file, "r") as f:
                for line in f:
                    if "=" in line and namse in line:
                        name, val = line.strip().split("=")
                        self.config[name] = val
                        return self.config[namse]
        except FileNotFoundError as e:
            self._create_if_not_exist()
            print("""
            
            File Not Found... With this error
            ================================
            {}
            ================================
            Creating now
            """.format(str(e)))
    def _get_config_value_debugger(self, namse):
        try:
            with open(self.config_file, "r") as f:
                for line in f:
                    if "=" in line and namse in line:
                        name, val = line.strip().split("=")
                        self.config[name] = val
                        print("""
            [Configure.py          Debug Mode]
            ==================================
            {}
            **********Config Values***********
            Name: {}
            Value: {}
            **********************************
            ==================================          
                        """.format(line, name, val))
                        return self.config[namse]
        except FileNotFoundError as e:
            self._create_if_not_exist()
            print("""
            
            File Not Found... With this error
            ================================
            {}
            ================================
            Creating now
            """.format(str(e)))
    def set_config_value(self, namse):
        pass
    


        
            
if __name__ == '__main__':
    c = Configure()
    print(str(c._get_config_value_debugger("Age")))